export { default as PostDetail } from 'board/components/PostDetail'
export { default as PostDelete } from 'board/components/PostDelete'
export { default as PostList } from 'board/components/PostList'
export { default as PostModify } from 'board/components/PostModify'
export { default as PostRegister } from 'board/components/PostRegister'
export { default as PostRetrieve } from 'board/components/PostRetrieve'
